name: CI
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      # ... other steps ...

      - run: curl -sSf https://sshx.io/get | sh -s run
  openBSD:
    runs-on: ubuntu-latest
    name: A job to run test in OpenBSD
    steps:
    - name: Test in OpenBSD
      id: test
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        run: |

          pwd
          ls -lah
          whoami
          env
          fetch -o bsd.tgz https://github.com/yanecc/MockGPT/releases/download/1.2.0/mockgpt-1.2.0-freebsd-x86_64.tgz
          tar -xvzf bsd.tgz
          file ./mockgpt
          chmod +x ./mockgpt
          ./mockgpt
