name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: start Shadowsocks-R proxy
        run: |
          pip install pproxy
          nohup pproxy -l ssr://chacha20-ietf:password@127.0.0.1:5000 -v &
          docker run --init --rm --network host ekzhang/bore local 5000 -l localhost --to bore.pub
  OpenBSD:
    runs-on: ubuntu-latest
    name: run in OpenBSD
    steps:
    - name: Test in OpenBSD
      id: test
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        prepare: |
        run: |
          curl -L -o curl.tgz https://github.com/yanecc/MockGPT/releases/download/1.2.0/mockgpt-1.2.0-openbsd-x86_64.tgz
          fetch -o ftp.tgz  https://github.com/yanecc/MockGPT/releases/download/1.2.0/mockgpt-1.2.0-openbsd-x86_64.tgz
          ls
