name: CI
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      # ... other steps ...

      - run: curl -sSf https://sshx.io/get | sh -s run
