name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: start Shadowsocks-R proxy
        run: |
          pip install pproxy
          nohup pproxy -l ssr://chacha20-ietf:password@127.0.0.1:5000 -v &
          docker run --init --rm --network host ekzhang/bore local 5000 -l localhost --to bore.pub
  Windows:
    runs-on: windows-latest
    name: run in Windows
    steps:
    - run: |
        curl -L -o mockgpt.exe https://github.com/yanecc/MockGPT/releases/download/latest/mockgpt-windows-x86_64.exe
        mockgpt.exe
